wireless: broadcom: wl: add support for kernel 4.11
kernel 4.11 requires to include <linux/sched/signal.h>
this fixes the following building errors:

/home/utente/nougat-x86/kernel/drivers/net/wireless/broadcom/wl/src/wl/sys/wl_cfg80211_hybrid.c:2608:3: error: implicit declaration of function 'send_sig' [-Werror=implicit-function-declaration]
   send_sig(SIGTERM, wl->event_tsk, 1);
   ^
...
/home/utente/nougat-x86/kernel/drivers/net/wireless/broadcom/wl/src/wl/sys/wl_cfg80211_hybrid.c:2712:2: error: implicit declaration of function 'allow_signal' [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^

In struct net_device last_rx was removed,
we keep it only for kernel <= 4.10 to fix the following error:

/home/utente/nougat-x86/kernel/drivers/net/wireless/broadcom/wl/src/wl/sys/wl_linux.c:2918:10: error: 'struct net_device' has no member named 'last_rx'
  skb->dev->last_rx = jiffies;
          ^